version: "3.7"
services:
  dyposten-nginx:
    container_name: "dyposten-server"
    image: "nginx:latest"
    restart: always
    ports:
      - "9000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - dyposten-php
      - dyposten-mysql
    links:
      - dyposten-php
    command: [nginx-debug, "-g", "daemon off;"]
    networks:
      dyposten-net:

  dyposten-php:
    container_name: "dyposten-php"
    restart: always
    volumes:
      - .:/var/www:delegated
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    depends_on:
      - dyposten-mysql
    links:
      - dyposten-mysql
    networks:
      dyposten-net:

  dyposten-mysql:
    container_name: "dyposten-mysql"
    image: "mysql"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      dyposten-net:

networks:
  dyposten-net:
    external: true
